### ISSUE TITLE
Ошибка при сборке fap'ом

### ISSUE THREAD

**Issue by GeniusRUS** [Ka3u6y6a/flipper-zero-dice#1]
Пытаюсь собрать [онлайн-сборщиком](https://flipc.org/Ka3u6y6a/flipper-zero-dice?branch=main), не удаётся, вываливается стактрейс:

`
applications_user/dice_dnd_app/dice_app.c: In function 'draw_callback': applications_user/dice_dnd_app/dice_app.c:192:26: error: implicit declaration of function 'acquire_mutex' [-Werror=implicit-function-declaration] 192 | const State* state = acquire_mutex((ValueMutex*)ctx, 25); | ^~~~~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:192:41: error: 'ValueMutex' undeclared (first use in this function) 192 | const State* state = acquire_mutex((ValueMutex*)ctx, 25); | ^~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:192:41: note: each undeclared identifier is reported only once for each function it appears in applications_user/dice_dnd_app/dice_app.c:192:52: error: expected expression before ')' token 192 | const State* state = acquire_mutex((ValueMutex*)ctx, 25); | ^ applications_user/dice_dnd_app/dice_app.c:207:5: error: implicit declaration of function 'release_mutex' [-Werror=implicit-function-declaration] 207 | release_mutex((ValueMutex*)ctx, state); | ^~~~~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:207:31: error: expected expression before ')' token 207 | release_mutex((ValueMutex*)ctx, state); | ^ applications_user/dice_dnd_app/dice_app.c:191:49: error: unused parameter 'ctx' [-Werror=unused-parameter] 191 | static void draw_callback(Canvas* canvas, void* ctx) { | ~~~~~~^~~ applications_user/dice_dnd_app/dice_app.c: In function 'dice_dnd_app': applications_user/dice_dnd_app/dice_app.c:233:5: error: unknown type name 'ValueMutex' 233 | ValueMutex state_mutex; | ^~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:234:9: error: implicit declaration of function 'init_mutex' [-Werror=implicit-function-declaration] 234 | if(!init_mutex(&state_mutex, state, sizeof(State))) { | ^~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:255:32: error: implicit declaration of function 'acquire_mutex_block' [-Werror=implicit-function-declaration] 255 | State* state = (State*)acquire_mutex_block(&state_mutex); | ^~~~~~~~~~~~~~~~~~~ applications_user/dice_dnd_app/dice_app.c:330:5: error: implicit declaration of function 'delete_mutex' [-Werror=implicit-function-declaration] 330 | delete_mutex(&state_mutex); | ^~~~~~~~~~~~ cc1: all warnings being treated as errors scons: *** [build/f7-firmware-D/.extapps/dice_dnd_app/dice_app.o] Error 1
`

Возможно поправить код, чтобы сборка была успешной?

**Comment by Ka3u6y6a** [comment]
Исправлено в коммите [ee31d41](https://github.com/Ka3u6y6a/flipper-zero-dice/commit/ee31d410db79ed39802f42cee00ed6df22162b02)
