### ISSUE TITLE
Crashes flipper zero on latest momentum firmware

### ISSUE THREAD

**Issue by AmikadM** [Ka3u6y6a/flipper-zero-dice#6]
When I try to run the app on the latest momentum firmware, the flipper crashes with the error null pointer dereference. Please fix

**Comment by Ka3u6y6a** [comment]
Hello @AmikadM. 
I checked it on momentum firmware (version mntm-004) and app version 1.2 from the [official store](https://lab.flipper.net/apps/dice_app) - everything works fine.

Could you please let me know where you downloaded the app from?

**Comment by AmikadM** [comment]
Idk I think it was already installed with momentum firmware and I tried updating it trough the flipper app but it didn't work

**Comment by Ka3u6y6a** [comment]
I didn't see the pre-installed DnD Dice app in the [momentum repository](https://github.com/Next-Flip/Momentum-Apps).  Perhaps the app remained from a previous firmware or previous firmware version.

Try deleting it (for example, with [qFlipper](https://flipperzero.one/update)) and reinstalling it from the official store again.

**Comment by AmikadM** [comment]
That worked, thx a lot! 
I just needed to uninstall and reinstall with the flipper app but now I wonder why updating doesn't work

**Comment by Ka3u6y6a** [comment]
Nice. Glad that I could be of assistance.
